name: Build JMGODesktop Windows

on:
  workflow_dispatch:

jobs:
  build-windows-x64:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows Desktop
        run: |
          flutter config --enable-windows-desktop

      - name: Install LLVM
        run: |
          choco install llvm -y --version=15.0.2
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg $env:USERPROFILE\vcpkg
          cd $env:USERPROFILE\vcpkg
          .\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$env:USERPROFILE\vcpkg" | Out-File -FilePath $env:GITHUB_ENV -Append
          .\vcpkg.exe install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static

      - name: Download Sciter DLL
        run: |
          New-Item -ItemType Directory -Force -Path target\release
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.win/x64/sciter.dll" -OutFile "target\release\sciter.dll"

      - name: 修改服务器地址和客户端名称
        run: |
          # 修改 ID Server
          $configFiles = Get-ChildItem -Recurse -Filter "config.rs" -Path libs
          foreach ($file in $configFiles) {
            (Get-Content $file.FullName) -replace 'DEFAULT_RENDEZVOUS_SERVER.*?;', 'DEFAULT_RENDEZVOUS_SERVER: &str = "askair.cn";' | Set-Content $file.FullName
          }
          # 修改名称
          (Get-Content Cargo.toml) -replace 'name = "rustdesk"', 'name = "JMGODesktop"' | Set-Content Cargo.toml
          Write-Output "✅ READER askair.cn + JMGODesktop"

      - name: Build Release
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: JMGODesktop
        run: |
          Copy-Item "target\x86_64-pc-windows-msvc\release\rustdesk.exe" -Destination "JMGODesktop.exe"
          Copy-Item "JMGODesktop.exe" -Destination "JMGODesktop-qs.exe"   # -qs 后缀 = 默认管理员权限

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: JMGODesktop
          path: |
            JMGODesktop.exe
            JMGODesktop-qs.exe
